Repository hyochan/flutter_inapp_purchase, pull requests merged in 2019-10, with the labels that each got.

#109 Release 2.0.0+14
  CHANGELOG.md
  android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java
  pubspec.yaml
Labels: release

#111 release/2.0.1
  CHANGELOG.md
  README.md
  android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java
  example/lib/main.dart
  lib/flutter_inapp_purchase.dart
  lib/modules.dart
  pubspec.yaml
Labels: bugfix, release

#114 fix: decode response json for connection updates stream
  lib/flutter_inapp_purchase.dart
Labels: bugfix

#117 #116 changed Future<Null> to Future due to dart sdk change
  example/README.md
  example/lib/main.dart
  lib/flutter_inapp_purchase.dart
Labels: bugfix, enhancement
