Repository hyochan/flutter_inapp_purchase, pull requests merged in 2020-10, with the labels that each got.

#210 Fix typo
  README.md
Labels: doc

#216 Fix a typo (eneabled -> enabled)
  README.md
Labels: doc

#212 IAPItem deserialization fix
  lib/modules.dart
Labels: typo

#214 Adding introductoryPriceNumberIOS
  ios/Classes/FlutterInappPurchasePlugin.m
  lib/modules.dart
Labels: enhancement, ios

#231 Type casting resolved
  lib/modules.dart
Labels: types

#229 Migrate to android billing api v3
  CHANGELOG.md
  README.md
  android/build.gradle
  android/src/main/java/com/dooboolab/flutterinapppurchase/AmazonInappPurchasePlugin.java
  android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java
  lib/flutter_inapp_purchase.dart
  lib/modules.dart
  pubspec.yaml
  test/flutter_inapp_purchase_test.dart
Labels: android, hacktoberfest-accepted, migration
