Repository hyochan/flutter_inapp_purchase, pull requests merged in 2021-11, with the labels that each got.

#316 some amazon fixes/additions i had to figure out
  KINDLE.md
  android/src/main/java/com/dooboolab/flutterinapppurchase/AmazonInappPurchasePlugin.java
Labels: android, doc, amazon

#325 Ios promocodes
  CHANGELOG.md
  README.md
  android/.project
  android/.settings/org.eclipse.buildship.core.prefs
  example/android/.project
  example/android/.settings/org.eclipse.buildship.core.prefs
  ios/Classes/FlutterInappPurchasePlugin.m
  lib/flutter_inapp_purchase.dart
  pubspec.yaml
Labels: feature

#313 Support for Amazon devices with Google Play sideloaded
  android/src/main/java/com/dooboolab/flutterinapppurchase/FlutterInappPurchasePlugin.java
Labels: enhancement

#326 Migrate to android billing client 4.0.0
  .coveralls.yml
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  android/build.gradle
  android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java
  example/lib/main.dart
  lib/modules.dart
  lib/utils.dart
  pubspec.yaml
Labels: android, migration, release

#327 Chagne CI to codecov
  .github/workflows/ci.yml
  README.md
Labels: ci

#328 Run on UiThread and few others
  android/src/main/java/com/dooboolab/flutterinapppurchase/AmazonInappPurchasePlugin.java
  android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java
  android/src/main/java/com/dooboolab/flutterinapppurchase/FlutterInappPurchasePlugin.java
  android/src/main/java/com/dooboolab/flutterinapppurchase/MethodResultWrapper.java
  lib/flutter_inapp_purchase.dart
  lib/utils.dart
  test/utils_test.dart
Labels: enhancement

#333 Purchase dialog pops twice issue resolved
  android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java
Labels: android, bugfix
